### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [sndels/graze#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119220580-d95b0a00-bb1d-11eb-96df-4b4c8e3a171d.png)

thank you  
best regards to you  
William

**Comment by sndels** [comment]
Hey William,
That error is from the binary itself and I recall similar stuff being resolved by reinstalling the nvidia graphics driver. I don't have access to a linux box at the moment but I pushed a patch including the most recent glfw release in case that fixes the issue.

**Comment by sndels** [comment]
Closing as inactive
